export default {
  explorer: {
    id: '',
    type: 'explorer',
    name: 'Explorer',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [
      {
        id: 'tab_1',
        title: 'Documents',
        active: true,
      },
    ],
    style: {
      top: 0,
      left: 0,
      height: '800px',
      width: '1200px',
      zIndex: 5,
    },
  },
  settings: {
    id: '',
    type: 'settings',
    name: 'Settings',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [],
    style: {
      top: 0,
      left: 0,
      height: '800px',
      width: '1200px',
      zIndex: 5,
    },
  },
  word: {
    id: '',
    type: 'word',
    name: 'Microsoft Word',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [],
    style: {
      top: 0,
      left: 0,
      height: '500px',
      width: '500px',
      zIndex: 5,
    },
  },
  edge: {
    id: '',
    type: 'edge',
    name: 'Microsoft Edge',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [],
    style: {
      top: 0,
      left: 0,
      height: '900px',
      width: '1200px',
      zIndex: 5,
    },
  },
  powerpoint: {
    id: '',
    type: 'powerpoint',
    name: 'Microsoft PowerPoint',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [],
    style: {
      top: 0,
      left: 0,
      height: '500px',
      width: '500px',
      zIndex: 5,
    },
  },
  steam: {
    id: '',
    type: 'steam',
    name: 'Steam',
    isSelected: false,
    isMinimized: false,
    isEnlarged: false,
    tabs: [],
    style: {
      top: 0,
      left: 0,
      height: '500px',
      width: '500px',
      zIndex: 5,
    },
  },
} as const
